# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Piráti Česká Třebová
email: pardubicko@pirati.cz
description: # this means to ignore newlines until "baseurl:"
            Prosazujeme fungující moderní politiku založenou na využití technologií 21. století pro otevřenou demokratickou společnost.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ceskatrebova.pirati.cz" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-get-json

paginate_path: "/aktuality/:num/"
paginate: 11

exclude:
  - readme.md
  - Gemfile
  - Gemfile.lock
  - package.json
  - bower.json
  - gulpfile.js
  - node_modules
  - bower_components
  - vendor

sass:
    style: compressed

permalink: /tiskove-zpravy/:title.html
collections:
  people:
    output: true
    permalink: /lide/:path/
  program:
    output: true
    permalink: /volby-2018/program/:title/
  teams:
    output: true
    permalink: /pripoj-se/:title/
  elections:
    output: true
    permalink: /volby/:path/

defaults:   # defaults values for collection scope
  -
    scope:
      path: "_people"
    values:
      layout: "page"
      rbar: "people, foto"
  -
    scope:
      path: "_program/komunal2018"
    values:
      layout: "page"
      rbar: "program"
  -
    scope:
      path: "_program/psp2017"
    values:
      layout: "page"
      rbar: "program program_item"
  -
    scope:
      path: "_teams"
    values:
      layout: "team"
      rbar: "team-summary, teams-toc"
  -
    scope:
      path: "_elections"
    values:
      layout: "kandidatka"

administrator:
    email: jiri.duchacek@pirati.cz

calendar: https://calendar.google.com/calendar/embed?showTitle=0&amp;showNav=0&amp;showDate=0&amp;showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;showTz=0&amp;mode=AGENDA&amp;height=500&amp;wkst=2&amp;hl=cs&amp;bgcolor=%23FFFFFF&amp;src=kddvdvu3adcjef2kro4j6mm838%40group.calendar.google.com&amp;color=%232952A3&amp;ctz=Europe%2FPrague
fb_name: Piráti Česká Třebová
fb: https://www.facebook.com/piratiCT/
tw: PiratskaStrana
instagramm: https://www.instagram.com/pirati.cz/
gplus: https://plus.google.com/u/0/+piratskastrana

emptyArray: []
peoplesOnForum: https://forum.pirati.cz/pardubicky-kraj-g35.html

jekyll_get_json:
  - data: members
    json: 'https://graph.pirati.cz/deadbeef-babe-f002-000000000599/members'

