# Welcome to Jekyll!
administrator:
  email: jiri.duchacek@pirati.cz, jan.suchanek@gmail.com, tomas.grosskopf@pirati.cz
github:
  url: https://github.com/pirati-web/ceskatrebova.pirati.cz/
  branch: master
url: "https://ceskatrebova.pirati.cz"

title: Piráti Česká Třebová
email: pardubicko@pirati.cz
description: Prosazujeme fungující moderní politiku založenou na využití technologií 21. století pro otevřenou demokratickou společnost.
keywords: Piráti, česká pirátská strana, svoboda, demokracie, Piráti Praha 11, piráti na jižáku, Jižní Město

organization:
  name: Místní sdružení Pirátů Česká Třebová
  shortName: Piráti Česká Třebová
  email: pardubicko@pirati.cz
  contactUid: 
  phone: +420 770 113 647
  address: |
    Na Moráni 3
    120 00 Praha 2
  #residenceImg: miscellaneous.jpg
  mapLink: https://mapy.cz/s/2N7Yv
  redmineLink: https://redmine.pirati.cz/projects/praha-11
  dataBoxId: b2i4r6j
  transparentAccount: 2100048174/2010
  transparentAccountSpecificSymbol: 110111
  donateLink: https://dary.pirati.cz/podpor-kraj/praha/
  onboardingLink: https://nalodeni.pirati.cz/

contactSummaryItems:
  - type: organizationEmail
  - type: organizationRedmineLink
  - type: organizationTransparentAccount
    includeMoreLink: true
  - type: organizationDataBox
  - type: piratiRootWebsite

calendar:
  # To enable a nicer calendar, make sure you start jekyll with GOOGLE_CALENDAR_APIKEY=[apikey] bundle exec jekyll serve
  title: Nadcházející události
  #id: kddvdvu3adcjef2kro4j6mm838@group.calendar.google.com
  #page: https://calendar.google.com/calendar/embed?showTitle=0&amp;showNav=0&amp;showDate=0&amp;showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;showTz=0&amp;mode=AGENDA&amp;height=500&amp;wkst=2&amp;hl=cs&amp;bgcolor=%23FFFFFF&amp;src=kddvdvu3adcjef2kro4j6mm838%40group.calendar.google.com&amp;color=%232952A3&amp;ctz=Europe%2FPrague  
  id: 7r673rlh255oforhv3oeb2l0g0@group.calendar.google.com
  page: https://calendar.google.com/calendar/embed?showTitle=0&showNav=0&showDate=0&showPrint=0&showTabs=0&showCalendars=0&showTz=0&mode=AGENDA&height=500&wkst=2&hl=cs&bgcolor=%23FFFFFF&src=kddvdvu3adcjef2kro4j6mm838%40group.calendar.google.com&color=%232952A3&ctz=Europe%2FPrague

facebook:
  profilePage: https://www.facebook.com/piratiCT/
  loadSDK: true
  appId: 1526197851008996

twitter:
  profile: PiratskaStrana
  loadSDK: true

instagram:
  profilePage: https://www.instagram.com/pirati.cz/

github:
  url: https://github.com/pirati-web/ceskatrebova.pirati.cz/
  branch: master

matomo:
  loadSDK: true
  siteId: 68

forum:
  page: https://forum.pirati.cz/pardubicky-kraj-g35.html

youtube:
  channel: UC_zxYLGrkmrYazYt0MzyVlA

twitter:
  loadSDK: true
  profile: piratipraha

instagram:
  profilePage: https://www.instagram.com/pirati.cz/

flicker:
  profilePage: https://www.flickr.com/photos/pirati/

styleguide_base_url: 'https://styleguide.pir-test.eu/latest'

############### SETTINSG #################

theme: jekyll-theme-pirati

# Build settings
markdown: kramdown
theme: jekyll-theme-pirati

pagination:
  per_page: 9
  permalink: '/:num/'
  title: ':title - stránka :num'
  trail: 7

exclude:
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - README.md
  - docker-compose.yml
  - vendor

permalink: /aktuality/:title.html
collections:
  people:
    output: true
    root: /clenove/
    permalink: /clenove/:path/    
  program:
    output: true
    permalink: /volby/:path

  # Sole purpose is to create candidate lists in separate files.
  candidatelists:
    output: false

defaults:   # defaults values for collection scope
  -
    scope:
      path: "_people"
    values:
      layout: "person"
      rbar:
        - profile
        - people
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
  -
    scope:
      path: "_program"
    values:
      layout: "program-post"
      rbar:
         - garant
         - program

assets:
  source_maps: true
  compression: true
  gzip: false
  plugins:
    img:
      optim:
        jpegoptim:
          strip: all
          max_quality: 80
    browsers:
      - "last 2 versions"
      - "IE > 9"
  sources:
    - assets/js
    - assets/img
    - vendor/bundle/ruby/2.5.0/gems/jekyll-theme-pirati-8.4.1/assets/img
